# Starter pipeline
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      git config --system core.longpaths true
      cd someserverpath //just a place to clone the repositories
      git clone --mirror https://github.com/HemanthNS/testrepo
      git remote set-url origin https://$(AdobeUsername):$(AdobePassword)@git.cloudmanager.adobe.com/program/programId
      git push --mirror
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev-test

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
